# Generated by Django 5.0.6 on 2024-05-29 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mailing_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='mail_subject',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='mail_text',
        ),
        migrations.AddField(
            model_name='mailing',
            name='name',
            field=models.CharField(default='Новая рассылка', max_length=100, verbose_name='название рассылки'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_subject', models.TextField(max_length=100, verbose_name='тема письма')),
                ('mail_text', models.TextField(verbose_name='тело письма')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailings.client', verbose_name='клиент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailings.message', verbose_name='сообщение'),
        ),
    ]
