# Generated by Django 5.0.6 on 2024-05-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_remove_mailing_mail_subject_remove_mailing_mail_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='client',
        ),
    ]
