# Generated by Django 5.0.6 on 2024-05-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0004_remove_message_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='is_view',
            field=models.BooleanField(default=False, verbose_name='признак просмотра'),
        ),
    ]
